<?php
/** login test */
// Initialize the session
session_start();

// Check if the user is logged in, if not then redirect him to login page
if(!isset($_SESSION["loggedin"]) || $_SESSION["loggedin"] !== true){
    header("location: usrLogin.php");
    exit;
}
?>


<!DOCTYPE html>
<html lang="en">
<link rel="stylesheet" type="text/css" href="teststyl.css">
<head>
    <meta charset="UTF-8">
    <title>Czujniki </title>

</head>
<body>
    <?php
    if($_SESSION["isPasswChanged"] !== true)
        echo '<div>
                <p style="background-color:#db1d1d; padding: 10px 10px; width:91.8%; font-weight: bold; ">
				Nie zresetowałeś jeszcze wygenerowanego przez system hasła.
				<br>
                Zrób to, aby zwiększyć bezpieczeństwo Twojego konta.</p>
              </div>'
    ?>
    <div class="header"><h1>Sieć czujników temperatury i wilgotności</h1></div>
        <div class="column navig">
            <ul>
				<li><a href="interfejsGlowny.phtml">Strona główna</a></li>
                <li><a href="genReport.php">Raporty</a></li> <!-- domyslna strona po zalogowaniu -->
				<?php
                    if(isset($_SESSION["permission"])&&$_SESSION["permission"]===true)
                    {
                        echo '<li><a href="interfejsCzujniki.php">Zarządzaj czujnikami</a></li>';
				    }
                    if(isset($_SESSION["permission"])&&$_SESSION["permission"]===true)
                    {
                        echo '<li><a href="addUser.php">Zarządzaj użytkownikami</a></li>';
                    }
                ?>

                <li><a href="setResetPassword.php">Zresetuj hasło</a></li>
                <li><a href="usrLogout.php">Wyloguj się</a></li>
            </ul>
        </div>
    <div class="column content">

        <?php include "tabelaCzujnikow.php"?>
        <?php include "tabelaPomiar.php"?>
    </div>

</body>
</html>