<?php
/** login test */
// Initialize the session
session_start();

// Check if the user is logged in, if not then redirect him to login page
if(!isset($_SESSION["loggedin"]) || $_SESSION["loggedin"] !== true){
    header("location: usrLogin.php");
    exit;
}
?>


<!DOCTYPE html>
<html lang="en">
<link rel="stylesheet" type="text/css" href="stylInterfejs.css">
<head>
    <meta charset="UTF-8">
    <title>Czujniki </title>

</head>
<body>
    <div class="header"><h1>Sieć czujników temperatury i wilgotności</h1></div>
        <div class="column navig">
            <ul>
                <li><a href="#">Unused</a></li>
                <li><a href="setResetPassword.php">Zresetuj hasło</a></li>
                <li><a href="usrLogout.php">Wyloguj się</a></li>
            </ul>
        </div>
    <div class="column content">

        <?php include "tabelaCzujnikow.php"?>
        <?php include "tabelaPomiar.php"?>
    </div>

</body>
</html>