<?php

/** login test */
// Initialize the session
session_start();

// Check if the user is logged in, if not then redirect him to login page
if(!isset($_SESSION["loggedin"]) || $_SESSION["loggedin"] !== true)
{
    header("location: usrLogin.php");
    exit;
}


if(isset($_SESSION["backup_success"]))
{
    if($_SESSION["backup_success"])$text = "Utworzono backup!";
    else $text = "Wystąpił błąd. Spróbuj ponownie późnej";
    unset($_SESSION["backup_success"]);
}
else
    $text="";

if(isset($_POST["backup"])/*&&$_POST["backup"]==="Utwórz backup"*/)
{
    require 'modules/config_db.php';
    $filename='database_backup_'.date('H-i-s_Y-m-d').'.sql';
    if(PHP_OS == 'WIN32'||PHP_OS =='WINNT' ||PHP_OS =='Windows')
        $result=exec('C:\xampp\mysql\bin\mysqldump.exe -h'.trim(DB_SERVER).
            ' -u'.trim(DB_USERNAME).' '.DB_NAME.' > backup\\'.$filename,$output);
    else
        $result=exec('mysqldump -h'.trim(DB_SERVER).
            ' -u'.trim(DB_USERNAME).' '.DB_NAME.' > backup/'.$filename,$output);

    if(empty($output)) $_SESSION["backup_success"]=true;
    else $_SESSION["backup_success"]=false;

    header('location: interfejsGlowny.phtml');
}



?>


<!DOCTYPE html>
<html lang="en">
<link rel="stylesheet" type="text/css" href="CSS/teststyl.css">
<head>
    <meta charset="UTF-8">
    <title>Czujniki </title>

</head>
<body>
    <?php
    if($_SESSION["isPasswChanged"] !== true)
        echo '<div>
                <p style="background-color:#db1d1d; padding: 10px 10px; width:91.8%; font-weight: bold; ">
				Nie zresetowałeś jeszcze wygenerowanego przez system hasła.
				<br>
                Zrób to, aby zwiększyć bezpieczeństwo Twojego konta.</p>
              </div>'
    ?>
    <div class="header"><h1>Sieć czujników temperatury i wilgotności</h1></div>
        <div class="column navig">
            <ul>
				<li><a href="interfejsGlowny.phtml">Strona główna</a></li>
                <li><a href="genReport.php">Raporty</a></li> <!-- domyslna strona po zalogowaniu -->
				<?php
                    if(isset($_SESSION["permission"])&&$_SESSION["permission"]===true)
                    {
                        echo '<li><a href="interfejsCzujniki.php">Zarządzaj czujnikami</a></li>';
				    }
                    if(isset($_SESSION["permission"])&&$_SESSION["permission"]===true)
                    {
                        echo '<li><a href="addUser.php">Zarządzaj użytkownikami</a></li>';
                    }
                ?>

                <li><a href="setResetPassword.php">Zresetuj hasło</a></li>
                <li><a href="usrLogout.php">Wyloguj się</a></li>
            </ul>
        </div>
    <div class="column content">

        <?php if(isset($_SESSION["permission"])&&$_SESSION["permission"]===true)
        {
            echo '<form action="'.htmlspecialchars($_SERVER["PHP_SELF"]).'" method="post">
            <input type="submit" class="myButton" name="backup" value="Utwórz backup">
            </form>';
            echo "<h3>$text</h3>";
        }
        ?>
        <?php include "modules/tabelaCzujnikow.php" ?>
        <?php include "modules/tabelaPomiar.php" ?>
    </div>

</body>
</html>